
/*CREATION DU BASE DE DONNES*/
CREATE DATABASE IF NOT EXISTS EMP;
 
      USE EMP;
/* CREATION DU TABLEAU COMPANY*/
CREATE TABLE IF NOT EXISTS COMPANY
        (  
           ID INT PRIMARY KEY NOT NULL,
            NAME VARCHAR(20) NOT NULL,
             AGE INT NOT NULL,
              ADDRESSE VARCHAR(100),
               SALARY REAL
        );
/* INSERTION DES DONNES */       
	INSERT INTO COMPANY (ID,NAME,AGE,ADDRESSE,SALARY)
          VALUES(3,'AHMAD',26,'ITALIE',25000.00),
                (5,'FIRAS',23,'TUNISIA',35000.00),
                (6,'BILAL',34,'FRANCE',21000.00);

/* Creation du user name */
CREATE USER JAS@localhost IDENTIFIED BY '123';
	CREATE USER IF NOT EXISTS JAS@localhost;
SELECT USER , HOST FROM MYSQL.USER;

GRANT SELECT, INSERT , UPDATE , DELETE , CREATE , DROP 
ON EMP.* TO JAS@localhost
WITH GRANT OPTION;

SHOW GRANTS FOR JAS@localhost;

GRANT ALL 
ON *.* TO JAS@localhost
WITH GRANT OPTION;

SHOW GRANTS FOR JAS@localhost;

/*DROP USER*/
DROP USER JAS@localhost;
